# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yong/Program/project/wechat_location_analyze_tool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yong/Program/project/wechat_location_analyze_tool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yong/Program/project/wechat_location_analyze_tool/CMakeFiles /home/yong/Program/project/wechat_location_analyze_tool/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yong/Program/project/wechat_location_analyze_tool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named analyze

# Build rule for target.
analyze: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 analyze
.PHONY : analyze

# fast build rule for target.
analyze/fast:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/build
.PHONY : analyze/fast

src/analyze.o: src/analyze.cc.o

.PHONY : src/analyze.o

# target to build an object file
src/analyze.cc.o:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/analyze.cc.o
.PHONY : src/analyze.cc.o

src/analyze.i: src/analyze.cc.i

.PHONY : src/analyze.i

# target to preprocess a source file
src/analyze.cc.i:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/analyze.cc.i
.PHONY : src/analyze.cc.i

src/analyze.s: src/analyze.cc.s

.PHONY : src/analyze.s

# target to generate assembly for a file
src/analyze.cc.s:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/analyze.cc.s
.PHONY : src/analyze.cc.s

src/process.o: src/process.cc.o

.PHONY : src/process.o

# target to build an object file
src/process.cc.o:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/process.cc.o
.PHONY : src/process.cc.o

src/process.i: src/process.cc.i

.PHONY : src/process.i

# target to preprocess a source file
src/process.cc.i:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/process.cc.i
.PHONY : src/process.cc.i

src/process.s: src/process.cc.s

.PHONY : src/process.s

# target to generate assembly for a file
src/process.cc.s:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/process.cc.s
.PHONY : src/process.cc.s

src/review.o: src/review.cc.o

.PHONY : src/review.o

# target to build an object file
src/review.cc.o:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/review.cc.o
.PHONY : src/review.cc.o

src/review.i: src/review.cc.i

.PHONY : src/review.i

# target to preprocess a source file
src/review.cc.i:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/review.cc.i
.PHONY : src/review.cc.i

src/review.s: src/review.cc.s

.PHONY : src/review.s

# target to generate assembly for a file
src/review.cc.s:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/review.cc.s
.PHONY : src/review.cc.s

src/statistic.o: src/statistic.cc.o

.PHONY : src/statistic.o

# target to build an object file
src/statistic.cc.o:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/statistic.cc.o
.PHONY : src/statistic.cc.o

src/statistic.i: src/statistic.cc.i

.PHONY : src/statistic.i

# target to preprocess a source file
src/statistic.cc.i:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/statistic.cc.i
.PHONY : src/statistic.cc.i

src/statistic.s: src/statistic.cc.s

.PHONY : src/statistic.s

# target to generate assembly for a file
src/statistic.cc.s:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/statistic.cc.s
.PHONY : src/statistic.cc.s

src/util.o: src/util.cc.o

.PHONY : src/util.o

# target to build an object file
src/util.cc.o:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/util.cc.o
.PHONY : src/util.cc.o

src/util.i: src/util.cc.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.cc.i:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/util.cc.i
.PHONY : src/util.cc.i

src/util.s: src/util.cc.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.cc.s:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/util.cc.s
.PHONY : src/util.cc.s

src/wechat.o: src/wechat.cc.o

.PHONY : src/wechat.o

# target to build an object file
src/wechat.cc.o:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/wechat.cc.o
.PHONY : src/wechat.cc.o

src/wechat.i: src/wechat.cc.i

.PHONY : src/wechat.i

# target to preprocess a source file
src/wechat.cc.i:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/wechat.cc.i
.PHONY : src/wechat.cc.i

src/wechat.s: src/wechat.cc.s

.PHONY : src/wechat.s

# target to generate assembly for a file
src/wechat.cc.s:
	$(MAKE) -f CMakeFiles/analyze.dir/build.make CMakeFiles/analyze.dir/src/wechat.cc.s
.PHONY : src/wechat.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... analyze"
	@echo "... src/analyze.o"
	@echo "... src/analyze.i"
	@echo "... src/analyze.s"
	@echo "... src/process.o"
	@echo "... src/process.i"
	@echo "... src/process.s"
	@echo "... src/review.o"
	@echo "... src/review.i"
	@echo "... src/review.s"
	@echo "... src/statistic.o"
	@echo "... src/statistic.i"
	@echo "... src/statistic.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... src/wechat.o"
	@echo "... src/wechat.i"
	@echo "... src/wechat.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

